/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spp;

import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SMKN1Rembang-PC
 */
public class petugas extends javax.swing.JFrame {

    /**
     * Creates new form petugas
     */
    DefaultTableModel modelPembayaran,modelSiswaBayar;
    
    int barisdatatabelsiswa;
    public petugas() {
        initComponents();
        tanggalbayar.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
        tampilDataSiswa();
        tampilDataPembayaran();
        fillPetugas();
        tampilFill();
        idpembayaran.setVisible(false);
        idangkatan.setVisible(false);
        idpetugas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboard = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        txtjumlahsiswa = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        name5 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        txtjumlahkelas = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        name7 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        txtjumlahspp = new javax.swing.JLabel();
        pembayaran = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelsiswabayar = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelbayar = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nisnsiswa = new javax.swing.JLabel();
        namasiswa = new javax.swing.JLabel();
        kelassiwa = new javax.swing.JLabel();
        angkatansiswa = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        idpetugas = new javax.swing.JLabel();
        tanggalbayar = new javax.swing.JLabel();
        tbayar = new javax.swing.JButton();
        namepetugas = new javax.swing.JLabel();
        idangkatan = new javax.swing.JLabel();
        jumlahbayar = new javax.swing.JTextField();
        bulandibayar = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        idpembayaran = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        carisiswa = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        printdata = new javax.swing.JTextArea();
        data = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                logout(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        dashboard.setBackground(new java.awt.Color(153, 153, 153));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Name");

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Selamat Datang,");
        name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name1MouseClicked(evt);
            }
        });

        name2.setBackground(new java.awt.Color(255, 255, 255));
        name2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("System Informasi Pembayaran Spp Sekolah");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 100));

        name3.setBackground(new java.awt.Color(255, 255, 255));
        name3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/school_students_icon_144607.png"))); // NOI18N

        name4.setBackground(new java.awt.Color(255, 255, 255));
        name4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name4.setText("Jumlah Siswa");

        txtjumlahsiswa.setBackground(new java.awt.Color(255, 255, 255));
        txtjumlahsiswa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtjumlahsiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtjumlahsiswa.setText("angka");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtjumlahsiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(name4, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            .addComponent(name3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtjumlahsiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 100));

        name5.setBackground(new java.awt.Color(255, 255, 255));
        name5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/google-classroom.png"))); // NOI18N

        name6.setBackground(new java.awt.Color(255, 255, 255));
        name6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name6.setText("Jumlah Kelas");

        txtjumlahkelas.setBackground(new java.awt.Color(255, 255, 255));
        txtjumlahkelas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtjumlahkelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtjumlahkelas.setText("angka");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(name6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
            .addComponent(txtjumlahkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtjumlahkelas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 100));

        name7.setBackground(new java.awt.Color(255, 255, 255));
        name7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/money.png"))); // NOI18N

        name8.setBackground(new java.awt.Color(255, 255, 255));
        name8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        name8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name8.setText("Jumlah Uang Spp");

        txtjumlahspp.setBackground(new java.awt.Color(255, 255, 255));
        txtjumlahspp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtjumlahspp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtjumlahspp.setText("angka");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(name8, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
            .addComponent(txtjumlahspp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtjumlahspp)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addGap(151, 151, 151)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addGap(148, 148, 148)))
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addGap(118, 118, 118))))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(208, 208, 208)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DASHBOARD", dashboard);

        pembayaran.setBackground(new java.awt.Color(153, 153, 153));
        pembayaran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pembayaran.setPreferredSize(new java.awt.Dimension(1365, 688));

        tabelsiswabayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelsiswabayar.setRowHeight(20);
        tabelsiswabayar.setSelectionBackground(new java.awt.Color(128, 128, 128));
        tabelsiswabayar.setShowVerticalLines(false);
        tabelsiswabayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelsiswabayarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelsiswabayar);

        tabelbayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbayar.setRowHeight(20);
        tabelbayar.setSelectionBackground(new java.awt.Color(128, 128, 128));
        tabelbayar.setShowVerticalLines(false);
        tabelbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbayarMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tabelbayar);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("NISN                   :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(250, 250, 250));
        jLabel18.setText("NAMA                  :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(250, 250, 250));
        jLabel19.setText("KELAS                 :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(250, 250, 250));
        jLabel20.setText("ANGKATAN        :");

        nisnsiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nisnsiswa.setForeground(new java.awt.Color(250, 250, 250));
        nisnsiswa.setText("~");
        nisnsiswa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nisnsiswaPropertyChange(evt);
            }
        });

        namasiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namasiswa.setForeground(new java.awt.Color(250, 250, 250));
        namasiswa.setText("~");

        kelassiwa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kelassiwa.setForeground(new java.awt.Color(250, 250, 250));
        kelassiwa.setText("~");

        angkatansiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        angkatansiswa.setForeground(new java.awt.Color(250, 250, 250));
        angkatansiswa.setText("~");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(250, 250, 250));
        jLabel21.setText("PETUGAS            :");

        idpetugas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idpetugas.setText("~");

        tanggalbayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggalbayar.setForeground(new java.awt.Color(250, 250, 250));
        tanggalbayar.setText("tanggal");

        tbayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/money.png"))); // NOI18N
        tbayar.setText("Bayar");
        tbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbayarActionPerformed(evt);
            }
        });

        namepetugas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namepetugas.setForeground(new java.awt.Color(250, 250, 250));
        namepetugas.setText("~");

        idangkatan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idangkatan.setText("~");

        bulandibayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(250, 250, 250));
        jLabel22.setText("BULAN                :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(250, 250, 250));
        jLabel23.setText("BAYAR                : ");

        idpembayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idpembayaran.setText("~");

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Cetak.png"))); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        carisiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carisiswaKeyReleased(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Cari Siswa");

        printdata.setColumns(20);
        printdata.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        printdata.setRows(5);
        jScrollPane10.setViewportView(printdata);

        data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        data.setForeground(new java.awt.Color(250, 250, 250));
        data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/pembayaran.png"))); // NOI18N
        data.setText("Data Transaksi Pembayaran");

        javax.swing.GroupLayout pembayaranLayout = new javax.swing.GroupLayout(pembayaran);
        pembayaran.setLayout(pembayaranLayout);
        pembayaranLayout.setHorizontalGroup(
            pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pembayaranLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idangkatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idpembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                    .addGroup(pembayaranLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(tanggalbayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel31)
                        .addGap(27, 27, 27)
                        .addComponent(carisiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pembayaranLayout.createSequentialGroup()
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(nisnsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pembayaranLayout.createSequentialGroup()
                                .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pembayaranLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bulandibayar, 0, 100, Short.MAX_VALUE)
                                            .addComponent(jumlahbayar)))
                                    .addGroup(pembayaranLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pembayaranLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(namasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pembayaranLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(kelassiwa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pembayaranLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(angkatansiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                    .addGap(32, 32, 32))
                                .addGroup(pembayaranLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(namepetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        pembayaranLayout.setVerticalGroup(
            pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data)
                    .addComponent(tanggalbayar)
                    .addComponent(carisiswa)
                    .addComponent(jLabel31))
                .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pembayaranLayout.createSequentialGroup()
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pembayaranLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(idpetugas)
                        .addGap(34, 34, 34)
                        .addComponent(idangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(idpembayaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 92, Short.MAX_VALUE)))
                .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pembayaranLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(nisnsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(namasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(kelassiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(angkatansiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(namepetugas))
                        .addGap(18, 18, 18)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bulandibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jScrollPane10))
                .addContainerGap())
        );

        jTabbedPane1.addTab("PEMBAYARAN", pembayaran);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1304, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_logout
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar","Warning",2)==JOptionPane.YES_OPTION){
            login login = new login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logout

    private void tabelsiswabayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelsiswabayarMouseClicked
        // TODO add your handling code here:
        barisdatatabelsiswa = tabelsiswabayar.getSelectedRow();

        nisnsiswa.setText(String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 0)));
        namasiswa.setText(String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 2)));
        kelassiwa.setText(String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 3)));
        angkatansiswa.setText(String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 6)));

        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT id_spp FROM siswa WHERE nisn LIKE '%"+nisnsiswa.getText()+"%'");
            while(rs.next()){
                idangkatan.setText(rs.getString("id_spp"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        bulandibayar.setSelectedItem("Pilih");
        jumlahbayar.setText("");
        tbayar.setText("Bayar");
        cetak();
    }//GEN-LAST:event_tabelsiswabayarMouseClicked

    private void tabelbayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbayarMouseClicked
        // TODO add your handling code here:
        int barisTabelPembayaran = tabelbayar.getSelectedRow();

        idpembayaran.setText(String.valueOf(tabelbayar.getValueAt(barisTabelPembayaran, 0)));
        bulandibayar.setSelectedItem(String.valueOf(tabelbayar.getValueAt(barisTabelPembayaran, 2)));
        konversiNormal1(String.valueOf(tabelbayar.getValueAt(barisTabelPembayaran, 5)));
        tbayar.setText("Lunasi");
    }//GEN-LAST:event_tabelbayarMouseClicked

    private void nisnsiswaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nisnsiswaPropertyChange
        tampilDataPembayaran();
    }//GEN-LAST:event_nisnsiswaPropertyChange

    private void tbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbayarActionPerformed
        String _petugas = idpetugas.getText();
        String nisn = nisnsiswa.getText();
        String tglbayar = tanggalbayar.getText();
        String bulanbayar = bulandibayar.getSelectedItem().toString();
        String tahun = angkatansiswa.getText();
        String id_spp = idangkatan.getText();
        String bayar = jumlahbayar.getText();
        if(tbayar.getText().equals("Bayar")){
            try {
                ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT * FROM pembayaran WHERE tahun_dibayar='"+tahun+"' AND bulan_dibayar='"+bulanbayar+"'");

                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Transaksi Sudah Dilakukan");
                }else{
                    if(_petugas.equals("~") || nisn.equals("~") || id_spp.equals("~") || bayar.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Harus Diisi");
                    }else{
                        try {
                            Statement st = koneksi.getConnection().createStatement();
                            st.executeUpdate("INSERT INTO pembayaran VALUES(null,'"+_petugas+"','"+nisn+"','"+tglbayar+"','"+bulanbayar+"','"+tahun+"','"+id_spp+"','"+bayar+"','')");
                            JOptionPane.showMessageDialog(null, "Berhasil Melakukan Transaksi");
                            cetak();
                            reset();
                            tampilDataPembayaran();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else if(tbayar.getText().equals("Lunasi")){
            try {
                Statement st = koneksi.getConnection().createStatement();
                st.executeUpdate("UPDATE pembayaran SET jumlah_bayar='"+bayar+"' WHERE id_pembayaran='"+idpembayaran.getText()+"'");
                JOptionPane.showMessageDialog(null, "Berhasil Melunasi");
                cetak();
                reset();
                tampilDataPembayaran();
                tbayar.setText("Bayar");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_tbayarActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            printdata.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void carisiswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carisiswaKeyReleased
        // TODO add your handling code here:
        CariSiswaBayar();
    }//GEN-LAST:event_carisiswaKeyReleased

    private void name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name1MouseClicked

    }//GEN-LAST:event_name1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angkatansiswa;
    private javax.swing.JComboBox<String> bulandibayar;
    private javax.swing.JTextField carisiswa;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel data;
    private javax.swing.JLabel idangkatan;
    private javax.swing.JLabel idpembayaran;
    private javax.swing.JLabel idpetugas;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jumlahbayar;
    private javax.swing.JLabel kelassiwa;
    private javax.swing.JLabel namasiswa;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel namepetugas;
    private javax.swing.JLabel nisnsiswa;
    private javax.swing.JPanel pembayaran;
    private javax.swing.JButton print;
    private javax.swing.JTextArea printdata;
    private javax.swing.JTable tabelbayar;
    private javax.swing.JTable tabelsiswabayar;
    private javax.swing.JLabel tanggalbayar;
    private javax.swing.JButton tbayar;
    private javax.swing.JLabel txtjumlahkelas;
    private javax.swing.JLabel txtjumlahsiswa;
    private javax.swing.JLabel txtjumlahspp;
    // End of variables declaration//GEN-END:variables
private void tampilDataPembayaran() {
        String[] header = {"ID TRANSAKSI","TANGGAL","BULAN","TAHUN","NOMINAL","BAYAR","STATUS"};
        modelPembayaran = new DefaultTableModel(header,0);
        tabelbayar.setModel(modelPembayaran);
        String dataStat = "SELECT * FROM pembayaran INNER JOIN spp ON pembayaran.id_spp = spp.id_spp WHERE nisn='"+nisnsiswa.getText()+"'";
        
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery(dataStat);
            while(rs.next()) {
               String no = rs.getString("id_pembayaran");
               String tanggal = rs.getString("tgl_bayar");
               String bulan = rs.getString("bulan_dibayar");
               String tahun = rs.getString("tahun_dibayar");
               double nominal = rs.getDouble("nominal");
               double jumlah = rs.getDouble("jumlah_bayar");
               String status = rs.getString("status");
               
               DecimalFormat kursRupiah = (DecimalFormat) DecimalFormat.getCurrencyInstance();
               DecimalFormatSymbols formatRupiah = new DecimalFormatSymbols();
                
               formatRupiah.setCurrencySymbol("Rp ");
               formatRupiah.setMonetaryDecimalSeparator('.');
                
               kursRupiah.setDecimalFormatSymbols(formatRupiah);
               
               Object [] record = {no,tanggal,bulan,tahun,kursRupiah.format(nominal),kursRupiah.format(jumlah),status};
               modelPembayaran.addRow(record);
           }
        }catch(SQLException e) {
           System.out.println(e);
        }
    }

    private void konversiNormal1(String x){
        DecimalFormat kursRupiah = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRupiah = new DecimalFormatSymbols();
 
        formatRupiah.setCurrencySymbol("Rp ");
        formatRupiah.setMonetaryDecimalSeparator('.');
 
        kursRupiah.setDecimalFormatSymbols(formatRupiah);
        try {
            Number number = kursRupiah.parse(x);
            double nilai = number.intValue();
            jumlahbayar.setText(String.format("%.0f", nilai));
        } catch (ParseException ex) {
            System.out.println(ex);
        }
    }

    private void tampilDataSiswa(){
        String [] kolomSiswa = {"NISN","NIS","NAMA","KELAS","ALAMAT","NO TELEPON","TAHUN","NOMINAL SPP"};
        modelSiswaBayar = new DefaultTableModel(kolomSiswa,0);
        tabelsiswabayar.setModel(modelSiswaBayar);
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT nisn,nis,nama,kelas,alamat,no_telp,tahun,nominal FROM siswa INNER JOIN spp ON siswa.id_spp = spp.id_spp INNER JOIN kelas ON siswa.id_kelas = kelas.id_kelas");
            while(rs.next()){
                String nisn = rs.getString("nisn");
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String nama_kelas = rs.getString("kelas");
                String no_telp = rs.getString("no_telp");
                String alamat = rs.getString("alamat");
                String tahun = rs.getString("tahun");
                double spp = rs.getDouble("nominal");
                
                DecimalFormat kursRupiah = (DecimalFormat) DecimalFormat.getCurrencyInstance();
                DecimalFormatSymbols formatRupiah = new DecimalFormatSymbols();
               
                formatRupiah.setCurrencySymbol("Rp. ");
                formatRupiah.setMonetaryDecimalSeparator('.');
                formatRupiah.setGroupingSeparator('.');
                kursRupiah.setDecimalFormatSymbols(formatRupiah);
                
                Object [] fields = {nisn,nis,nama,nama_kelas,alamat,no_telp,tahun,kursRupiah.format(spp)};
                modelSiswaBayar.addRow(fields);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);            
        }
    }
    
    private void fillPetugas(){
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT * FROM petugas WHERE username='"+login.tusername.getText()+"'");
            while(rs.next()){
                idpetugas.setText(rs.getString("id_petugas"));
                namepetugas.setText(rs.getString("nama_petugas"));
            }
        } catch (SQLException e) {
        }
    }
    
    private void reset(){
        bulandibayar.setSelectedItem("Pilih");
        jumlahbayar.setText("");
    }
    
        private void cetak(){
        printdata.setText("================================================================\n");
        printdata.setText(printdata.getText()+"NISN\t : "+String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 0))+"\n");
        printdata.setText(printdata.getText()+"NIS\t : "+String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 1))+"\n");
        printdata.setText(printdata.getText()+"NAMA\t : "+String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 2))+"\n");
        printdata.setText(printdata.getText()+"KELAS\t : "+String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 3))+"\n");
        printdata.setText(printdata.getText()+"TAHUN\t : "+String.valueOf(tabelsiswabayar.getValueAt(barisdatatabelsiswa, 6))+"\n");
        printdata.setText(printdata.getText()+"================================================================\n");
        printdata.setText(printdata.getText()+"TANGGAL\tBULAN\tNOMINAL\tBAYAR\tSTATUS\tSISA\n");
        printdata.setText(printdata.getText()+"================================================================\n");
        String dataStat = "SELECT tgl_bayar,bulan_dibayar,nominal,jumlah_bayar,status,spp.nominal - pembayaran.jumlah_bayar AS sisa FROM pembayaran INNER JOIN spp ON pembayaran.id_spp = spp.id_spp WHERE nisn='"+nisnsiswa.getText()+"'";
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery(dataStat);
            while(rs.next()) {
               String tanggal = rs.getString("tgl_bayar");
               String bulan = rs.getString("bulan_dibayar");
               double nominal = rs.getDouble("nominal");
               double jumlah = rs.getDouble("jumlah_bayar");
               String status = rs.getString("status");
               double sisa = rs.getDouble("sisa");
               
               DecimalFormat kursRupiah = (DecimalFormat) DecimalFormat.getCurrencyInstance();
               DecimalFormatSymbols formatRupiah = new DecimalFormatSymbols();
               
               formatRupiah.setCurrencySymbol("Rp. ");
               formatRupiah.setMonetaryDecimalSeparator('.');
               formatRupiah.setGroupingSeparator('.');
               kursRupiah.setDecimalFormatSymbols(formatRupiah);
               
               printdata.setText(printdata.getText()+tanggal+"\t"+bulan+"\t"+kursRupiah.format(nominal)+"\t"+kursRupiah.format(jumlah)+"\t"+status+"\t"+kursRupiah.format(sisa)+"\n");
               printdata.setText(printdata.getText()+"================================================================\n");
            }
            ResultSet data = koneksi.getConnection().createStatement().executeQuery("SELECT SUM(nominal) AS total,SUM(jumlah_bayar) AS total_bayar,SUM(spp.nominal - pembayaran.jumlah_bayar) AS sisa FROM pembayaran INNER JOIN spp ON pembayaran.id_spp = spp.id_spp WHERE nisn='"+nisnsiswa.getText()+"' ");
            while (data.next()) {                
               double total = data.getDouble("total");
               double totalbayar = data.getDouble("total_bayar");
               double sisa = data.getDouble("sisa");
               
               DecimalFormat kursRupiah = (DecimalFormat) DecimalFormat.getCurrencyInstance();
               DecimalFormatSymbols formatRupiah = new DecimalFormatSymbols();
               
               formatRupiah.setCurrencySymbol("Rp. ");
               formatRupiah.setMonetaryDecimalSeparator('.');
               formatRupiah.setGroupingSeparator('.');
               kursRupiah.setDecimalFormatSymbols(formatRupiah);
               
               printdata.setText(printdata.getText()+"\tTOTAL:\t"+kursRupiah.format(total)+"\t"+kursRupiah.format(totalbayar)+"\t\t"+sisa);
               
            }
        }catch(SQLException e) {
           System.out.println(e);
        }
    }
    
    private void CariSiswaBayar(){
        String [] kolomSiswaBayar = {"NISN","NIS","NAMA","KELAS","ALAMAT","NO TELEPON","TAHUN","NOMINAL SPP"};
        modelSiswaBayar = new DefaultTableModel(kolomSiswaBayar,0);
        tabelsiswabayar.setModel(modelSiswaBayar);
        try {
            ResultSet rs = koneksi.getConnection().createStatement().executeQuery("SELECT nisn,nis,nama,kelas,alamat,no_telp,tahun,nominal FROM siswa INNER JOIN spp ON siswa.id_spp = spp.id_spp INNER JOIN kelas ON siswa.id_kelas = kelas.id_kelas WHERE nama LIKE '%"+carisiswa.getText()+"%' ");
            while(rs.next()){
                String nisn = rs.getString("nisn");
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String nama_kelas = rs.getString("kelas");
                String no_telp = rs.getString("no_telp");
                String alamat = rs.getString("alamat");
                String tahun = rs.getString("tahun");
                String spp = rs.getString("nominal");
                String [] fields = {nisn,nis,nama,nama_kelas,alamat,no_telp,tahun,spp};
                modelSiswaBayar.addRow(fields);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);            
        }
    }
    
    private void tampilFill(){
        try{
            ResultSet nama = koneksi.getConnection().createStatement().executeQuery("SELECT nama_petugas FROM petugas WHERE username='"+login.tusername.getText()+"'");
            while(nama.next()){
                name.setText(nama.getString("nama_petugas"));
            }
            
            ResultSet jumlahKelas = koneksi.getConnection().createStatement().executeQuery("SELECT COUNT(kelas) FROM KELAS ");
            while(jumlahKelas.next()){
                txtjumlahkelas.setText(jumlahKelas.getString(1));
            }
            
            ResultSet jumlahSiswa = koneksi.getConnection().createStatement().executeQuery("SELECT COUNT(nama) FROM SISWA");
            while(jumlahSiswa.next()){
                txtjumlahsiswa.setText(jumlahSiswa.getString(1));
            }
            
            ResultSet jumlahSpp = koneksi.getConnection().createStatement().executeQuery("SELECT SUM(jumlah_bayar) FROM pembayaran");
            while(jumlahSpp.next()){
                double uang = jumlahSpp.getDouble(1);
                
                DecimalFormat kursRupiah = (DecimalFormat) DecimalFormat.getCurrencyInstance();
                DecimalFormatSymbols formatRupiah = new DecimalFormatSymbols();
               
                formatRupiah.setCurrencySymbol("Rp ");
                formatRupiah.setMonetaryDecimalSeparator('.');
                formatRupiah.setGroupingSeparator('.');
                kursRupiah.setDecimalFormatSymbols(formatRupiah);
                
                txtjumlahspp.setText(kursRupiah.format(uang));
            }
            
        }catch(SQLException x){
            System.out.println(x);
        }
    }
}
